server:
  port: 9090

vault:
  addr: http://localhost:8200
  token: root

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/payments
    username: root
    password: password