# Deployment for the injector
{{ template "vault.mode" . }}
{{- if and (ne .mode "") (and ((eq (.Values.global.enabled | toString) "true") (eq (.Values.injector.enabled | toString) "true")))}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "vault.fullname" . }}-injector
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "vault.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "vault.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      component: injector
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "vault.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        component: injector
    spec:
      serviceAccountName: "{{ template "vault.fullname" . }}-injector"
      containers:
        - name: sidecar-injector
          image: "{{ .Values.injector.image }}"
          imagePullPolicy: IfNotPresent
          args:
            - agent-inject
{{- if .Values.injector.tls.secretName }}
            - -tls-cert-file=/etc/webhook/certs/{{ .Values.injector.tls.certName }}
            - -tls-key-file=/etc/webhook/certs/{{ .Values.injector.tls.keyName }}
{{- else }}
            - -tls-auto={{ template "vault.fullname" . }}-agent-injector-cfg
            - -tls-auto-hosts={{ template "vault.fullname" . }}-agent-injector-svc,{{ template "vault.fullname" . }}-agent-injector-svc.{{ .Release.Namespace }},{{ template "vault.fullname" . }}-agent-injector-svc.{{ .Release.Namespace }}.svc
{{- end }}
            - -vault-address={{ template "vault.fullname" . }}
            - -vault-image={{ .Values.global.image }}
            - 2>&1
{{- if .Values.injector.tls.secretName }}
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: "{{ .Values.injector.tls.secretName }}"
{{- end }}
{{ end }}
